// frontend/src/app/features/auth/login.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ToastService } from '../../shared/services/toast.service';
import { HeaderComponent, FooterComponent } from '../../shared/components';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule, HeaderComponent, FooterComponent],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;
  showPassword = false;
  loading = false;
  error: string | null = null;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private toastService: ToastService,
    private router: Router
  ) {
    this.initForm();
  }

  ngOnInit(): void {}

  private initForm(): void {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      rememberMe: [false]
    });
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      return;
    }

    this.loading = true;
    this.error = null;

    const credentials = {
      email: this.loginForm.get('email')?.value,
      password: this.loginForm.get('password')?.value
    };

    console.log('LoginComponent.onSubmit - Iniciando login con:', { email: credentials.email, password: '***' });

    this.authService.login(credentials).subscribe({
      next: (response) => {
        try {
          console.log('LoginComponent - Login exitoso:', response);
          const successMsg = '¡Bienvenido de vuelta!';
          console.log('LoginComponent - Mostrando toast success con mensaje:', successMsg);
          this.toastService.success(successMsg);
          setTimeout(() => {
            this.router.navigate(['/dashboard']);
          }, 500);
        } catch (e) {
          console.error('LoginComponent - Exception en success handler:', e);
        } finally {
          this.loading = false;
        }
      },
      error: (err) => {
        try {
          console.log('LoginComponent - Error en login:', err);
          console.log('LoginComponent - err.error:', err.error);
          console.log('LoginComponent - err.status:', err.status);
          console.log('LoginComponent - err.statusText:', err.statusText);
          
          // Extraer mensaje de error del API
          let errorMessage = 'Error en el inicio de sesión. Verifique sus credenciales.';
          
          if (err.error?.message) {
            errorMessage = err.error.message;
          } else if (err.error?.errors) {
            // Si hay errores de validación
            const errorMessages = [];
            for (const field in err.error.errors) {
              if (Array.isArray(err.error.errors[field])) {
                errorMessages.push(err.error.errors[field][0]);
              }
            }
            if (errorMessages.length > 0) {
              errorMessage = errorMessages.join('. ');
            }
          } else if (err.statusText) {
            errorMessage = err.statusText;
          }
          
          console.log('LoginComponent - errorMessage final:', errorMessage);
          console.log('LoginComponent - Mostrando toast error con mensaje:', errorMessage);
          
          this.toastService.error(errorMessage);
          this.error = errorMessage;
        } catch (e) {
          console.error('LoginComponent - Exception en error handler:', e);
          this.toastService.error('Error inesperado. Por favor intente de nuevo.');
        } finally {
          this.loading = false;
        }
      }
    });
  }

  getFieldError(fieldName: string): string | null {
    const field = this.loginForm.get(fieldName);
    if (!field || !field.errors || !field.touched) return null;

    if (field.errors['required']) return `${fieldName} es requerido`;
    if (field.errors['email']) return 'Email inválido';
    if (field.errors['minlength']) return `Mínimo ${field.errors['minlength'].requiredLength} caracteres`;

    return null;
  }
}

<div class="h-screen flex flex-col">
  <app-header></app-header>
  
  <main class="flex-1 flex items-center justify-center relative px-4 overflow-hidden">
    <!-- Background Decorative Elements -->
    <div class="absolute inset-0 bg-login-pattern pointer-events-none"></div>
    <div class="absolute top-1/4 -left-20 w-96 h-96 bg-primary/5 rounded-full blur-3xl pointer-events-none"></div>
    <div class="absolute bottom-1/4 -right-20 w-80 h-80 bg-tertiary/5 rounded-full blur-3xl pointer-events-none"></div>
    
    <!-- Login Container -->
    <div class="relative w-full max-w-[1100px] h-[85vh] flex bg-surface-container-lowest rounded-xl overflow-hidden shadow-[0_12px_40px_rgba(26,28,30,0.06)] border border-outline-variant/15">
      
      <!-- Branding/Image Side -->
      <div class="hidden md:flex w-1/2 relative overflow-hidden bg-primary-container">
        <img 
          class="absolute inset-0 w-full h-full object-cover mix-blend-overlay opacity-60" 
          alt="Modern minimalist office interior" 
          src="https://lh3.googleusercontent.com/aida-public/AB6AXuAQMKtXqq_PbKGDSCMZYNpR-eZ8noJdtxzRoywtPMEun0ncNyVDC9n9ntqEXTB_mpj3V-lzAJgM6g4V2bw8OWB1FHCyd1Qrw7Wl-3wjm_NaJ8DzGjnHm7-7SXKegPCWY_u547UCwTE2SCjSGo1phN9DcNCmKlUoLcLcwWnY886qQybZcqU9wVyHnieu5JGsQ04CAw6fE6jIgIo6iWsuz8Lb-vz-QXXRuaXtu_KMPbXsXST_aeQE_kyMb4bOZbza6PH9Lsc8BvCEwB_k"
        />
        <div class="relative z-10 p-12 flex flex-col justify-between h-full">
          <div>
            <div class="w-12 h-12 bg-white rounded-lg flex items-center justify-center mb-6">
              <span class="material-symbols-outlined text-primary text-3xl" style="font-variation-settings: 'FILL' 1">schedule</span>
            </div>
            <h1 class="font-headline text-4xl text-white leading-tight mb-4">
              Precisión en cada turno.
            </h1>
            <p class="text-white/80 text-lg max-w-sm">
              La plataforma definitiva para la optimización de capital humano y control de jornadas laborales.
            </p>
          </div>
          <div class="flex gap-4">
            <div class="flex flex-col">
              <span class="text-white font-bold text-2xl font-headline">99.8%</span>
              <span class="text-white/70 text-xs font-label uppercase tracking-wider">Exactitud</span>
            </div>
            <div class="w-px h-10 bg-white/20"></div>
            <div class="flex flex-col">
              <span class="text-white font-bold text-2xl font-headline">24/7</span>
              <span class="text-white/70 text-xs font-label uppercase tracking-wider">Monitoreo</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Form Side -->
      <div class="w-full md:w-1/2 p-6 md:p-10 flex flex-col justify-center bg-surface-container-lowest overflow-y-auto">
        <div class="mb-6">
          <h2 class="font-headline text-2xl font-bold text-on-surface mb-1">Bienvenido de nuevo</h2>
          <p class="text-on-surface-variant text-sm">Ingrese sus credenciales para acceder.</p>
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-4">
          <!-- Email Field -->
          <div class="space-y-1">
            <label class="block font-label text-[9px] text-on-surface-variant uppercase tracking-widest font-semibold" for="email">
              Usuario o correo
            </label>
            <div class="relative">
              <span class="absolute left-4 top-1/2 -translate-y-1/2 material-symbols-outlined text-outline text-sm">person</span>
              <input 
                class="w-full pl-10 pr-4 py-2 bg-surface-container-low border-none rounded-lg focus:ring-1 focus:ring-primary focus:bg-surface-container-lowest transition-all placeholder:text-outline/60 text-on-surface text-sm" 
                id="email" 
                formControlName="email"
                placeholder="ejemplo@empresa.com" 
                type="email"
              />
            </div>
            <p *ngIf="getFieldError('email')" class="text-error text-xs mt-0.5">{{ getFieldError('email') }}</p>
          </div>

          <!-- Password Field -->
          <div class="space-y-1">
            <div class="flex justify-between items-center">
              <label class="block font-label text-[9px] text-on-surface-variant uppercase tracking-widest font-semibold" for="password">
                Contraseña
              </label>
              <a class="text-primary text-[10px] font-medium hover:underline" href="#">¿Olvidó?</a>
            </div>
            <div class="relative">
              <span class="absolute left-4 top-1/2 -translate-y-1/2 material-symbols-outlined text-outline text-sm">lock</span>
              <input 
                class="w-full pl-10 pr-10 py-2 bg-surface-container-low border-none rounded-lg focus:ring-1 focus:ring-primary focus:bg-surface-container-lowest transition-all placeholder:text-outline/60 text-on-surface text-sm" 
                id="password" 
                formControlName="password"
                placeholder="••••••••" 
                [type]="showPassword ? 'text' : 'password'"
              />
              <button 
                class="absolute right-4 top-1/2 -translate-y-1/2 text-outline hover:text-primary transition-colors" 
                type="button"
                (click)="togglePasswordVisibility()"
              >
                <span class="material-symbols-outlined text-lg">{{ showPassword ? 'visibility_off' : 'visibility' }}</span>
              </button>
            </div>
            <p *ngIf="getFieldError('password')" class="text-error text-xs mt-0.5">{{ getFieldError('password') }}</p>
          </div>

          <!-- Remember Me -->
          <div class="flex items-center pt-1">
            <input 
              class="rounded border-outline-variant text-primary focus:ring-primary h-3 w-3 bg-surface-container-low" 
              id="remember" 
              formControlName="rememberMe"
              type="checkbox"
            />
            <label class="ml-2 block text-xs text-on-surface-variant" for="remember">Mantener sesión</label>
          </div>

          <!-- Submit Button -->
          <button 
            class="w-full py-3 bg-primary text-white font-semibold rounded-lg shadow-lg shadow-primary/20 hover:opacity-90 active:scale-[0.98] transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed text-sm" 
            type="submit"
            [disabled]="loading || loginForm.invalid"
          >
            <span>{{ loading ? 'Iniciando...' : 'Iniciar sesión' }}</span>
            <span class="material-symbols-outlined text-base">{{ loading ? 'autorenew' : 'login' }}</span>
          </button>
        </form>

        <!-- Register Link -->
        <div class="mt-4 text-center">
          <p class="text-xs text-on-surface-variant">
            ¿Sin cuenta? 
            <a routerLink="/register" class="text-primary font-bold hover:underline">Regístrate</a>
          </p>
        </div>
        
        <!-- Footer Info -->
        <div class="mt-6 pt-4 border-t border-outline-variant/10 flex flex-col gap-2">
          <div class="flex items-center gap-2 text-[9px] text-outline">
            <span class="material-symbols-outlined text-xs">verified_user</span>
            Conexión Segura
          </div>
          <p class="text-[8px] text-outline/60 leading-relaxed">
            © 2024 Gestión de Horarios. Acceso restringido.
          </p>
        </div>
      </div>
    </div>
  </main>

  <app-footer></app-footer>
</div>

// resources/js/Pages/Login.vue
<template>
    <div class="min-h-screen bg-slate-950 flex">
        <!-- Left Sidebar - Info Section -->
        <div class="hidden lg:flex lg:w-6/12 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 border-r border-slate-700/50 relative overflow-hidden">
            <!-- Background pattern subtle -->
            <div class="absolute inset-0 opacity-5">
                <div class="absolute top-0 left-0 w-96 h-96 bg-blue-400 rounded-full blur-3xl"></div>
                <div class="absolute bottom-0 right-0 w-96 h-96 bg-slate-400 rounded-full blur-3xl"></div>
            </div>

            <div class="relative z-10 flex flex-col justify-center p-12 space-y-12">
                <!-- Logo Section -->
                <div>
                    <div class="flex items-center gap-4 mb-8">
                        <div class="w-14 h-14 bg-gradient-to-br from-blue-500 to-slate-400 rounded-lg flex items-center justify-center">
                            <svg viewBox="0 0 64 64" class="w-8 h-8 text-slate-950" fill="currentColor">
                                <rect x="8" y="14" width="48" height="38" rx="3" fill="none" stroke="currentColor" stroke-width="2"/>
                                <line x1="8" y1="24" x2="56" y2="24" stroke="currentColor" stroke-width="2"/>
                                <line x1="8" y1="34" x2="56" y2="34" stroke="currentColor" stroke-width="2"/>
                                <line x1="8" y1="44" x2="56" y2="44" stroke="currentColor" stroke-width="2"/>
                                <circle cx="14" cy="28" r="1.5" fill="currentColor" opacity="0.8"/>
                                <circle cx="28" cy="28" r="1.5" fill="currentColor" opacity="0.6"/>
                                <circle cx="42" cy="28" r="1.5" fill="currentColor" opacity="0.4"/>
                            </svg>
                        </div>
                        <div>
                            <h1 class="text-2xl font-bold text-white">Horarios</h1>
                            <p class="text-xs text-slate-400 uppercase tracking-widest">Gestión de Turnos</p>
                        </div>
                    </div>
                    <div class="h-1 w-16 bg-gradient-to-r from-blue-500 to-transparent rounded-full"></div>
                </div>

                <!-- Features List -->
                <div class="space-y-8">
                    <div>
                        <h3 class="text-lg font-semibold text-white mb-2">Gestión Inteligente</h3>
                        <p class="text-sm text-slate-400 leading-relaxed">Organiza tu equipo con precisión. Crea, edita y visualiza horarios en tiempo real.</p>
                    </div>
                    
                    <div>
                        <h3 class="text-lg font-semibold text-white mb-2">Control Total</h3>
                        <p class="text-sm text-slate-400 leading-relaxed">Asigna turnos, gestiona cambios y mantén todo sincronizado con tu equipo.</p>
                    </div>
                    
                    <div>
                        <h3 class="text-lg font-semibold text-white mb-2">Reportes Precisos</h3>
                        <p class="text-sm text-slate-400 leading-relaxed">Accede a datos detallados sobre horarios, disponibilidad y cumplimiento.</p>
                    </div>
                </div>

                <!-- Bottom Info -->
                <div class="pt-8 border-t border-slate-700/50">
                    <p class="text-xs text-slate-500 mb-4">v1.0 Beta - Plataforma de Gestión de Horarios</p>
                    <div class="flex gap-4">
                        <a href="#" class="text-xs text-slate-400 hover:text-slate-200 transition-colors">Documentación</a>
                        <a href="#" class="text-xs text-slate-400 hover:text-slate-200 transition-colors">Soporte</a>
                        <a href="#" class="text-xs text-slate-400 hover:text-slate-200 transition-colors">Términos</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Right Section - Login Form -->
        <div class="w-full lg:w-6/12 bg-slate-950 flex flex-col justify-center items-center p-6 lg:p-12">
            <div class="w-full max-w-sm">
                <!-- Header -->
                <div class="mb-12">
                    <h2 class="text-3xl font-bold text-white mb-2">Bienvenido</h2>
                    <p class="text-slate-400 text-sm">Inicia sesión para continuar</p>
                </div>

                <!-- Accent line -->
                <div class="h-0.5 w-10 bg-gradient-to-r from-blue-500 to-transparent mb-12 rounded-full"></div>

                <!-- Form -->
                <form @submit.prevent="handleLogin" class="space-y-6">
                    <!-- Email Field -->
                    <div class="relative group">
                        <label class="block text-xs font-semibold text-slate-300 uppercase tracking-widest mb-3">
                            Correo Electrónico
                        </label>
                        <input
                            v-model="form.email"
                            type="email"
                            placeholder="tu@empresa.com"
                            class="w-full px-4 py-3 bg-slate-900/50 border border-slate-700 rounded-lg text-white placeholder-slate-500 transition-all duration-200 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/30 group-hover:border-slate-600"
                        />
                        <span v-if="errors.email" class="text-red-400 text-xs mt-2 block">{{ errors.email }}</span>
                    </div>

                    <!-- Password Field -->
                    <div class="relative group">
                        <label class="block text-xs font-semibold text-slate-300 uppercase tracking-widest mb-3">
                            Contraseña
                        </label>
                        <div class="relative">
                            <input
                                v-model="form.password"
                                :type="showPassword ? 'text' : 'password'"
                                placeholder="••••••••"
                                class="w-full px-4 py-3 bg-slate-900/50 border border-slate-700 rounded-lg text-white placeholder-slate-500 transition-all duration-200 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/30 group-hover:border-slate-600"
                            />
                            <button
                                type="button"
                                @click="showPassword = !showPassword"
                                class="absolute right-4 top-1/2 transform -translate-y-1/2 text-slate-400 hover:text-slate-200 transition-colors"
                            >
                                <svg v-if="!showPassword" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"/>
                                    <path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"/>
                                </svg>
                                <svg v-else class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clip-rule="evenodd"/>
                                </svg>
                            </button>
                        </div>
                        <span v-if="errors.password" class="text-red-400 text-xs mt-2 block">{{ errors.password }}</span>
                    </div>

                    <!-- Remember & Forgot -->
                    <div class="flex items-center justify-between pt-2">
                        <label class="flex items-center gap-2 cursor-pointer group">
                            <input
                                v-model="form.remember"
                                type="checkbox"
                                class="w-4 h-4 rounded border border-slate-600 bg-slate-900/50 checked:bg-blue-500 checked:border-blue-500 cursor-pointer accent-blue-500 transition-colors"
                            />
                            <span class="text-sm text-slate-400 group-hover:text-slate-300 transition-colors">Recuérdame</span>
                        </label>
                        <a href="#" class="text-sm text-blue-500 hover:text-blue-400 transition-colors">¿Olvidaste tu contraseña?</a>
                    </div>

                    <!-- Error message -->
                    <div v-if="loginError" class="bg-red-500/10 border border-red-500/30 rounded-lg p-3 text-red-400 text-sm">
                        {{ loginError }}
                    </div>

                    <!-- Submit Button -->
                    <button
                        type="submit"
                        :disabled="loading"
                        class="w-full py-3 px-4 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 disabled:text-slate-500 text-white font-semibold rounded-lg transition-all duration-200 transform hover:scale-[1.005] active:scale-[0.98] disabled:scale-100 disabled:cursor-not-allowed mt-8"
                    >
                        <span v-if="!loading">Iniciar Sesión</span>
                        <span v-else class="flex items-center justify-center gap-2">
                            <svg class="animate-spin w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
                                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/>
                            </svg>
                            Cargando...
                        </span>
                    </button>
                </form>

                <!-- Divider -->
                <div class="flex items-center gap-3 my-8">
                    <div class="flex-1 h-px bg-slate-700"></div>
                    <span class="text-xs text-slate-500 uppercase">O</span>
                    <div class="flex-1 h-px bg-slate-700"></div>
                </div>

                <!-- Register Link -->
                <div class="text-center">
                    <p class="text-slate-400 text-sm">
                        ¿No tienes cuenta?
                        <a href="/register" class="text-blue-500 hover:text-blue-400 font-semibold transition-colors">Crear cuenta</a>
                    </p>
                </div>

                <!-- Footer Info -->
                <div class="mt-12 pt-6 border-t border-slate-800">
                    <p class="text-xs text-slate-500 text-center">
                        Al iniciar sesión, aceptas nuestros términos de servicio y política de privacidad
                    </p>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import api from '@/Utils/api';

const form = ref({
    email: '',
    password: '',
    remember: false,
});

const showPassword = ref(false);
const loading = ref(false);
const errors = ref({});
const loginError = ref('');

const handleLogin = async () => {
    errors.value = {};
    loginError.value = '';

    if (!form.value.email) {
        errors.value.email = 'El correo es requerido';
    }
    if (!form.value.password) {
        errors.value.password = 'La contraseña es requerida';
    }

    if (Object.keys(errors.value).length > 0) return;

    loading.value = true;
    try {
        const response = await api.post('/login', {
            email: form.value.email,
            password: form.value.password,
            remember: form.value.remember,
        });

        localStorage.setItem('token', response.data.token);
        window.location.href = '/';
    } catch (error) {
        loginError.value = error.response?.data?.message || 'Error al iniciar sesión';
    } finally {
        loading.value = false;
    }
};
</script>

<style scoped>
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
</style>
