// frontend/src/app/features/auth/register.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ToastService } from '../../shared/services/toast.service';
import { FooterComponent } from '../../shared/components';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule, FooterComponent],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {
  registerForm!: FormGroup;
  showPassword = false;
  loading = false;
  error: string | null = null;
  success = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private toastService: ToastService,
    private router: Router,
    private cdr: ChangeDetectorRef
  ) {
    this.initForm();
  }

  ngOnInit(): void {}

  private initForm(): void {
    this.registerForm = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(8)]],
      passwordConfirm: ['', [Validators.required]],
      acceptTerms: [false, [Validators.requiredTrue]]
    }, {
      validators: this.passwordMatchValidator
    });
  }

  private passwordMatchValidator(form: FormGroup): { [key: string]: boolean } | null {
    const password = form.get('password');
    const passwordConfirm = form.get('passwordConfirm');

    if (password && passwordConfirm && password.value !== passwordConfirm.value) {
      passwordConfirm.setErrors({ passwordMismatch: true });
      return { passwordMismatch: true };
    }
    return null;
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  onSubmit(): void {
    if (this.registerForm.invalid) {
      this.registerForm.reset();
      return;
    }

    this.loading = true;
    this.cdr.markForCheck();

    const userData = {
      name: this.registerForm.get('name')?.value,
      email: this.registerForm.get('email')?.value,
      password: this.registerForm.get('password')?.value
    };

    this.authService.register(userData).subscribe({
      next: (response) => {
        this.toastService.success('¡Cuenta creada! Redirigiendo...');
        setTimeout(() => this.router.navigate(['/login']), 500);
      },
      error: (err) => {
        this.loading = false;
        this.cdr.markForCheck();
        let errorMessage = 'Error en el registro';
        if (err.error?.message) {
          errorMessage = err.error.message;
        }
        this.toastService.error(errorMessage);
        this.registerForm.reset();
      }
    });
  }

  getFieldError(fieldName: string): string | null {
    const field = this.registerForm.get(fieldName);
    if (!field || !field.errors || !field.touched) return null;

    if (field.errors['required']) return `${fieldName} es requerido`;
    if (field.errors['email']) return 'Email inválido';
    if (field.errors['minlength']) return `Mínimo ${field.errors['minlength'].requiredLength} caracteres`;
    if (field.errors['passwordMismatch']) return 'Las contraseñas no coinciden';
    if (field.errors['requiredTrue']) return 'Debe aceptar los términos de servicio';

    return null;
  }
}

<div class="bg-surface text-on-surface h-screen flex flex-col overflow-hidden">
  <div class="fixed inset-0 z-0 overflow-hidden pointer-events-none">
    <div class="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-primary/5 blur-[120px]"></div>
    <div class="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-tertiary/5 blur-[120px]"></div>
  </div>
  
  <main class="relative z-10 flex-1 flex items-center justify-center p-4 overflow-hidden">
    <div class="w-full max-w-5xl h-[90vh] grid grid-cols-1 md:grid-cols-12 bg-surface-container-lowest rounded-xl shadow-[0_12px_40px_rgba(26,28,30,0.06)] overflow-hidden border border-outline-variant/10">
      
      <!-- Branding/Image Side -->
      <div class="hidden md:flex md:col-span-5 bg-surface-container-low p-12 flex-col justify-between relative overflow-hidden">
        <div class="relative z-10">
          <div class="flex items-center gap-3 mb-8">
            <div class="w-10 h-10 bg-primary-gradient rounded-lg flex items-center justify-center text-white">
              <span class="material-symbols-outlined" style="font-variation-settings: 'FILL' 1">calendar_today</span>
            </div>
            <span class="text-xl font-bold tracking-tight text-on-surface">Gestión de Horarios</span>
          </div>
          <h2 class="text-4xl font-extrabold text-on-surface leading-tight mb-6">Optimiza el tiempo de tu equipo.</h2>
          <p class="text-on-surface-variant text-lg leading-relaxed">Únete a la plataforma líder para la coordinación de turnos y seguimiento de productividad en tiempo real.</p>
        </div>

        <!-- Testimonial -->
        <div class="relative z-10 mt-auto">
          <div class="bg-white/40 backdrop-blur-md p-4 rounded-lg border border-white/20">
            <div class="flex items-center gap-4">
              <div class="w-12 h-12 rounded-full bg-primary-fixed overflow-hidden ring-2 ring-white">
                <img 
                  alt="User" 
                  class="w-full h-full object-cover" 
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuChuye9apo75pIM6BYnUI20waHSrXXG-12JOeWg9VvtkCtcGww0w0ivLxDDd2wi7Q9BuBxOE1ybgy7KIaqHuF5AUtwMiaQGeSHezr3M4MprYdup6o4yOT1L673vfrHXiqDt4ZD_Q4FYyiFtkXqT8SPxraatns2wSPxlmcP5rTR1kwC6AZPH5jx5460xuufgQtINZrOPRMrEY7Fs4fM8yW_1JZXZgeGsMaHLAkrnuANVHDKVA-ymCLJ3PBVIU2AAMv1hhQ72hwS0VASU"
                  />
              </div>
              <div>
                <p class="text-sm font-semibold text-on-surface">"La mejor herramienta para RRHH"</p>
                <p class="text-xs text-on-surface-variant">Lucía M., Directora de Operaciones</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Background pattern -->
        <div class="absolute bottom-0 left-0 w-full h-1/2 opacity-10 pointer-events-none">
          <img 
            alt="Background pattern" 
            class="w-full h-full object-cover" 
            src="https://lh3.googleusercontent.com/aida-public/AB6AXuCHC7hE3iFaI2iPshTOcsUue6rjtpTwUsEV-ZQzoSbLhP2t0HaxpFUlc7cuUTUtapzrQvwfJJd_ZujRrxI_cyIlXjFFTGN1uCDXZBZYVBTGwvwJQUW69mLJLvmks6wPzRcBmV-Ia-lBzpW-75Nm8Xgpe2LK6v4L1zlkAHE9i1nzt0YkgIryTC4eTjI8v0Qagy-KzpLRdq37YsTtqI8IEbNUcVg4s4BctzAVKYqLYmsT5nNNwaL6aZvcKqEtVnt-JrU1S8jwQJnm3_x9"
          />
        </div>
      </div>

      <!-- Form Side -->
      <div class="col-span-1 md:col-span-7 p-6 md:p-8 flex flex-col justify-center overflow-y-auto">
        <div class="max-w-md mx-auto w-full">
          <div class="mb-6">
            <h1 class="text-2xl font-bold text-on-surface mb-1">Crear cuenta</h1>
            <p class="text-on-surface-variant text-xs">Ingresa tus datos para comenzar.</p>
          </div>

          <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-3">
            
            <!-- Nombre -->
            <div class="space-y-1">
              <label class="text-[9px] font-semibold tracking-wider text-on-surface-variant uppercase" for="name">
                Nombre completo
              </label>
              <div class="relative">
                <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-sm">person</span>
                <input 
                  class="w-full pl-9 pr-3 py-2 bg-surface-container-highest border-none rounded-lg focus:ring-2 focus:ring-primary focus:bg-surface-container-lowest transition-all text-on-surface placeholder:text-outline text-sm" 
                  id="name" 
                  formControlName="name"
                  placeholder="Ej. Juan Pérez" 
                  type="text"
                />
              </div>
              <p *ngIf="getFieldError('name')" class="text-error text-xs mt-0.5">{{ getFieldError('name') }}</p>
            </div>

            <!-- Correo -->
            <div class="space-y-1">
              <label class="text-[9px] font-semibold tracking-wider text-on-surface-variant uppercase" for="email">
                Correo electrónico
              </label>
              <div class="relative">
                <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-sm">mail</span>
                <input 
                  class="w-full pl-9 pr-3 py-2 bg-surface-container-highest border-none rounded-lg focus:ring-2 focus:ring-primary focus:bg-surface-container-lowest transition-all text-on-surface placeholder:text-outline text-sm" 
                  id="email" 
                  formControlName="email"
                  placeholder="usuario@empresa.com" 
                  type="email"
                />
              </div>
              <p *ngIf="getFieldError('email')" class="text-error text-xs mt-0.5">{{ getFieldError('email') }}</p>
            </div>

            <!-- Contraseña -->
            <div class="space-y-1">
              <label class="text-[9px] font-semibold tracking-wider text-on-surface-variant uppercase" for="password">
                Contraseña
              </label>
              <div class="relative">
                <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-sm">lock</span>
                <input 
                  class="w-full pl-9 pr-9 py-2 bg-surface-container-highest border-none rounded-lg focus:ring-2 focus:ring-primary focus:bg-surface-container-lowest transition-all text-on-surface placeholder:text-outline text-sm" 
                  id="password" 
                  formControlName="password"
                  placeholder="••••••••" 
                  [type]="showPassword ? 'text' : 'password'"
                />
                <button 
                  class="absolute right-3 top-1/2 -translate-y-1/2 text-outline hover:text-on-surface transition-colors" 
                  type="button"
                  (click)="togglePasswordVisibility()"
                >
                  <span class="material-symbols-outlined text-sm">{{ showPassword ? 'visibility_off' : 'visibility' }}</span>
                </button>
              </div>
              <p *ngIf="getFieldError('password')" class="text-error text-xs mt-0.5">{{ getFieldError('password') }}</p>
            </div>

            <!-- Confirmar Contraseña -->
            <div class="space-y-1">
              <label class="text-[9px] font-semibold tracking-wider text-on-surface-variant uppercase" for="passwordConfirm">
                Confirmar contraseña
              </label>
              <div class="relative">
                <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-sm">lock</span>
                <input 
                  class="w-full pl-9 pr-3 py-2 bg-surface-container-highest border-none rounded-lg focus:ring-2 focus:ring-primary focus:bg-surface-container-lowest transition-all text-on-surface placeholder:text-outline text-sm" 
                  id="passwordConfirm" 
                  formControlName="passwordConfirm"
                  placeholder="••••••••" 
                  type="password"
                />
              </div>
              <p *ngIf="getFieldError('passwordConfirm')" class="text-error text-xs mt-0.5">{{ getFieldError('passwordConfirm') }}</p>
            </div>

            <!-- Terms Agreement -->
            <div class="space-y-1">
              <div class="flex items-start gap-2 pt-1">
                <input 
                  class="rounded border-outline-variant text-primary focus:ring-primary h-3 w-3 mt-0.5 flex-shrink-0" 
                  id="acceptTerms" 
                  formControlName="acceptTerms"
                  type="checkbox"
                />
                <label class="text-[9px] text-on-surface-variant" for="acceptTerms">
                  Acepto los <a href="#" class="text-primary hover:underline">Términos</a> y <a href="#" class="text-primary hover:underline">Privacidad</a>
                </label>
              </div>
              <p *ngIf="getFieldError('acceptTerms')" class="text-error text-xs mt-0.5">{{ getFieldError('acceptTerms') }}</p>
            </div>

            <!-- Submit Button -->
            <button 
              class="w-full bg-primary-gradient text-white font-bold py-2.5 rounded-lg shadow-lg hover:opacity-90 transition-opacity flex items-center justify-center gap-2 group mt-3 disabled:opacity-50 disabled:cursor-not-allowed text-sm" 
              type="submit"
              [disabled]="loading || registerForm.invalid"
            >
              {{ loading ? 'Registrando...' : 'Registrar usuario' }}
              <span class="material-symbols-outlined group-hover:translate-x-1 transition-transform text-base">{{ loading ? 'autorenew' : 'arrow_forward' }}</span>
            </button>
          </form>

          <!-- Login Link -->
          <div class="mt-4 text-center">
            <p class="text-xs text-on-surface-variant">
              ¿Ya tienes cuenta? 
              <a routerLink="/" class="text-primary font-bold hover:underline">Inicia sesión</a>
            </p>
          </div>

          <!-- Footer Info -->
          <div class="mt-6 pt-4 border-t border-outline-variant/15 text-center">
            <p class="text-[8px] text-outline uppercase tracking-widest leading-tight">
              Al registrarte, aceptas nuestros términos y privacidad.
            </p>
          </div>
        </div>
      </div>
    </div>
  </main>

  <app-footer></app-footer>
</div>

// resources/js/Pages/Register.vue
<template>
    <div class="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 flex items-center justify-center p-4 sm:p-0 overflow-hidden">
        <!-- Toast Notifications -->
        <div class="fixed top-4 right-4 z-50 space-y-2">
            <transition-group name="toast">
                <div v-for="toast in toasts" :key="toast.id" :class="[
                    'px-4 py-3 rounded-lg text-white font-medium shadow-lg animate-in fade-in slide-in-from-right-4 duration-300',
                    toast.type === 'error' ? 'bg-red-500' : toast.type === 'success' ? 'bg-teal-600' : 'bg-blue-500'
                ]">
                    {{ toast.message }}
                </div>
            </transition-group>
        </div>
        <!-- Background Effects -->
        <div class="absolute inset-0 overflow-hidden">
            <div class="absolute -top-40 -right-40 w-80 h-80 bg-teal-600/10 rounded-full blur-3xl"></div>
            <div class="absolute -bottom-40 -left-40 w-80 h-80 bg-teal-600/5 rounded-full blur-3xl"></div>
        </div>

        <!-- Main Container -->
        <div class="w-screen h-screen grid grid-cols-1 lg:grid-cols-2 gap-0 relative z-10">
            <!-- Left Column -->
            <div class="hidden lg:flex lg:flex-col lg:justify-between p-12 bg-gradient-to-br from-slate-800 to-slate-900 border-r border-slate-700/50">
                <div>
                    <div class="inline-flex items-center gap-3 mb-20">
                        <div class="w-11 h-11 bg-gradient-to-br from-teal-600 to-teal-700 rounded-lg flex items-center justify-center shadow-lg shadow-teal-600/20">
                            <svg viewBox="0 0 64 64" class="w-6 h-6 text-white" fill="currentColor"><path d="M32 4C16.536 4 4 16.536 4 32s12.536 28 28 28 28-12.536 28-28S47.464 4 32 4zm0 52c-13.255 0-24-10.745-24-24s10.745-24 24-24 24 10.745 24 24-10.745 24-24 24z"/></svg>
                        </div>
                        <div>
                            <h1 class="text-2xl font-bold text-white">ShiftFlow</h1>
                            <p class="text-slate-400 text-xs font-medium tracking-wide">GESTIÓN INTELIGENTE</p>
                        </div>
                    </div>
                    <div class="space-y-8 mt-16">
                        <div class="group">
                            <div class="flex items-start gap-4">
                                <div class="w-10 h-10 bg-teal-600/10 rounded-lg flex items-center justify-center flex-shrink-0 group-hover:bg-teal-600/20 transition-colors">
                                    <svg class="w-5 h-5 text-teal-600" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 10 10.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/></svg>
                                </div>
                                <div>
                                    <h3 class="text-sm font-semibold text-white mb-1">Gestión Centralizada</h3>
                                    <p class="text-slate-400 text-xs leading-relaxed">Organiza todos tus turnos y equipos desde un único panel intuitivo</p>
                                </div>
                            </div>
                        </div>
                        <div class="group">
                            <div class="flex items-start gap-4">
                                <div class="w-10 h-10 bg-teal-600/10 rounded-lg flex items-center justify-center flex-shrink-0 group-hover:bg-teal-600/20 transition-colors">
                                    <svg class="w-5 h-5 text-teal-600" fill="currentColor" viewBox="0 0 20 20"><path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"/></svg>
                                </div>
                                <div>
                                    <h3 class="text-sm font-semibold text-white mb-1">Colaboración Fluida</h3>
                                    <p class="text-slate-400 text-xs leading-relaxed">Comunica, coordina y resuelve cambios en tiempo real</p>
                                </div>
                            </div>
                        </div>
                        <div class="group">
                            <div class="flex items-start gap-4">
                                <div class="w-10 h-10 bg-teal-600/10 rounded-lg flex items-center justify-center flex-shrink-0 group-hover:bg-teal-600/20 transition-colors">
                                    <svg class="w-5 h-5 text-teal-600" fill="currentColor" viewBox="0 0 20 20"><path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z"/></svg>
                                </div>
                                <div>
                                    <h3 class="text-sm font-semibold text-white mb-1">Reportes Avanzados</h3>
                                    <p class="text-slate-400 text-xs leading-relaxed">Análisis detallados y métricas en tiempo real</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="space-y-4">
                    <div class="flex items-center gap-2 text-slate-400 text-xs">
                        <div class="w-2 h-2 bg-teal-600 rounded-full"></div>
                        <span>Seguridad Empresarial</span>
                    </div>
                    <div class="flex items-center gap-2 text-slate-400 text-xs">
                        <div class="w-2 h-2 bg-teal-600 rounded-full"></div>
                        <span>GDPR Compliant</span>
                    </div>
                    <p class="text-slate-500 text-xs pt-4 border-t border-slate-700">© 2026 ShiftFlow. Todos los derechos reservados.</p>
                </div>
            </div>

            <!-- Right Column -->
            <div class="flex flex-col justify-center px-6 sm:px-12 py-16 sm:py-20 bg-slate-900/50 backdrop-blur-sm border border-slate-700/50 rounded-xl lg:rounded-none">
                <div class="w-full max-w-sm mx-auto">
                    <div class="mb-10">
                        <h2 class="text-4xl font-bold text-white mb-3">Crear Cuenta</h2>
                        <p class="text-slate-400 text-sm leading-relaxed">Ingresa tus datos para comenzar a gestionar tus turnos</p>
                    </div>

                    <form @submit.prevent="handleRegister()" class="space-y-4">
                        <div class="space-y-2.5">
                            <label class="block text-sm font-medium text-slate-300">Nombre Completo</label>
                            <input v-model="form.name" type="text" placeholder="Juan Pérez" class="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-600 text-white placeholder-slate-500"/>
                            <span v-if="errors.name" class="text-red-400 text-xs">{{ errors.name }}</span>
                        </div>

                        <div class="space-y-2.5">
                            <label class="block text-sm font-medium text-slate-300">Email</label>
                            <input v-model="form.email" type="email" placeholder="tu@empresa.com" class="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-600 text-white placeholder-slate-500"/>
                            <span v-if="errors.email" class="text-red-400 text-xs">{{ errors.email }}</span>
                        </div>

                        <div class="space-y-2.5">
                            <label class="block text-sm font-medium text-slate-300">Contraseña</label>
                            <div class="relative">
                                <input v-model="form.password" :type="showPassword ? 'text' : 'password'" placeholder="Mínimo 8 caracteres" class="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-600 text-white placeholder-slate-500 pr-10"/>
                                <button type="button" @click="showPassword = !showPassword" class="absolute right-3 top-1/2 transform -translate-y-1/2 text-slate-500 hover:text-teal-400">
                                    <svg v-if="!showPassword" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"/><path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"/></svg>
                                    <svg v-else class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clip-rule="evenodd"/></svg>
                                </button>
                            </div>
                            <span v-if="errors.password" class="text-red-400 text-xs">{{ errors.password }}</span>
                        </div>

                        <div class="space-y-2.5">
                            <label class="block text-sm font-medium text-slate-300">Confirmar Contraseña</label>
                            <div class="relative">
                                <input v-model="form.password_confirmation" :type="showConfirmPassword ? 'text' : 'password'" placeholder="Repite la contraseña" class="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-600 text-white placeholder-slate-500 pr-10"/>
                                <button type="button" @click="showConfirmPassword = !showConfirmPassword" class="absolute right-3 top-1/2 transform -translate-y-1/2 text-slate-500 hover:text-teal-400">
                                    <svg v-if="!showConfirmPassword" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"/><path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"/></svg>
                                    <svg v-else class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clip-rule="evenodd"/></svg>
                                </button>
                            </div>
                            <span v-if="errors.password_confirmation" class="text-red-400 text-xs">{{ errors.password_confirmation }}</span>
                        </div>

                        <div class="flex items-start gap-2 pt-2">
                            <input v-model="form.terms" type="checkbox" id="terms" class="w-4 h-4 bg-slate-800 border-slate-700 rounded accent-teal-600 mt-0.5 flex-shrink-0"/>
                            <label for="terms" class="text-xs text-slate-400">Acepto los <a href="#" class="text-teal-600 underline">términos de servicio</a> y la <a href="#" class="text-teal-600 underline">política de privacidad</a></label>
                        </div>



                        <button type="submit" :disabled="loading" class="w-full mt-8 py-3 bg-gradient-to-r from-teal-600 to-teal-700 hover:from-teal-600 hover:to-teal-700 disabled:from-slate-700 disabled:to-slate-700 text-white font-semibold rounded-lg transition-all disabled:cursor-not-allowed flex items-center justify-center gap-2">
                            <span v-if="!loading">Crear Cuenta</span>
                            <svg v-else class="animate-spin w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/></svg>
                        </button>
                    </form>

                    <div class="text-center mt-8">
                        <p class="text-slate-400 text-sm">¿Ya tienes cuenta?</p>
                        <a href="/login" class="text-emerald-500 hover:text-emerald-400 font-semibold text-sm">Accede aquí</a>
                    </div>

                    <div class="lg:hidden mt-12 pt-8 border-t border-slate-700 flex items-center gap-2 text-slate-500">
                        <svg class="w-4 h-4 text-teal-600" fill="currentColor" viewBox="0 0 64 64"><path d="M32 4C16.536 4 4 16.536 4 32s12.536 28 28 28 28-12.536 28-28S47.464 4 32 4zm0 52c-13.255 0-24-10.745-24-24s10.745-24 24-24 24 10.745 24 24-10.745 24-24 24z"/></svg>
                        <span class="text-xs">© 2026 ShiftFlow</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import api from '@/Utils/api';

const form = ref({name: '', email: '', password: '', password_confirmation: '', terms: false});
const showPassword = ref(false);
const showConfirmPassword = ref(false);
const loading = ref(false);
const errors = ref({});

// Toast notification system
const toasts = ref([]);
const showToast = (message, type = 'error', duration = 4000) => {
    const id = Date.now();
    const toast = { id, message, type };
    toasts.value.push(toast);
    if (duration > 0) setTimeout(() => { toasts.value = toasts.value.filter(t => t.id !== id); }, duration);
};

const validateForm = () => {
    errors.value = {};
    if (!form.value.name) errors.value.name = 'Nombre requerido';
    if (!form.value.email) errors.value.email = 'Email requerido';
    if (!form.value.password) errors.value.password = 'Contraseña requerida';
    if (form.value.password.length < 8) errors.value.password = 'Mínimo 8 caracteres';
    if (form.value.password !== form.value.password_confirmation) errors.value.password_confirmation = 'No coinciden';
    if (!form.value.terms) { showToast('Debes aceptar los términos'); return false; }
    return Object.keys(errors.value).length === 0;
};

const handleRegister = async () => {
    if (!validateForm()) return;
    loading.value = true;
    try {
        const payload = {
            name: form.value.name,
            email: form.value.email,
            password: form.value.password,
            password_confirmation: form.value.password_confirmation,
            role: 'trabajador'
        };
        await api.post('/auth/register', payload);
        showToast('¡Cuenta creada! Inicia sesión.', 'success');
        form.value = {name: '', email: '', password: '', password_confirmation: '', terms: false};
        setTimeout(() => { window.location.href = '/login'; }, 1500);
    } catch (err) {
        const msg = err.response?.data?.errors?.role?.[0] || err.response?.data?.message || 'Error al registrarse';
        showToast(msg, 'error');
    } finally {
        loading.value = false;
    }
};
</script>

<style scoped>
input::-webkit-outer-spin-button, input::-webkit-inner-spin-button { -webkit-appearance: none; margin: 0; }
</style>
